// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lckeanbaatdjclgskxke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxja2VhbmJhYXRkamNsZ3NreGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0OTkxMDUsImV4cCI6MjA1NzA3NTEwNX0.veoxzvRIWuuuda4MNbsMvZAPtHQfypIYhHqjTDQD4pQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);